---
- hosts: vm1
  become_user: root
  remote_user: vagrant
  gather_facts: true
  
  tasks:
    - name: Generating key pairs
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
      become: yes

    - name: Copying id_rsa.pub key from VM1
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /id_rsa1.pub
        remote_src: yes
      become: yes

    - name: Copying authorized_keys from VM1 (contains Docker pub key)
      copy:
        src: ~/.ssh/authorized_keys
        dest: /auth_key
        remote_src: yes
      become: yes


- hosts: vm2
  become_user: root
  remote_user: vagrant
  gather_facts: true
  
  tasks:
    - name: Generating key pairs
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
      become: yes
    
    - name: Copying id_rsa.pub key from VM2
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /id_rsa2.pub
        remote_src: yes
      become: yes


- hosts: vm3
  become_user: root
  remote_user: vagrant
  gather_facts: true
  
  tasks:
    - name: Generating key pairs
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
      become: yes
    
    - name: Copying id_rsa.pub key from VM3
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /id_rsa3.pub
        remote_src: yes
      become: yes


- hosts: localhost
  become_user: root
  gather_facts: true
  
  tasks:
    - name: Appending all public keys to /authorized_keys
      shell: |
        cat /id_rsa1.pub > /authorized_keys
        cat /id_rsa2.pub >> /authorized_keys
        cat /id_rsa3.pub >> /authorized_keys
        cat /auth_key >> /authorized_keys
        rm -f /id_rsa[1-3].pub /auth_key
      become: yes

- hosts: vm1 vm2 vm3
  become_user: root
  remote_user: vagrant
  gather_facts: true

  tasks:
    - name: Sending VMs the authorized_keys
      copy:
        src: /authorized_keys
        dest: ~/.ssh/authorized_keys
        remote_src: no
      become: yes